#!/usr/bin/env bash
# displays information about subdomains.

subinfo(){
    if [ "$#" -eq 1 ]; then
        dig www."$1" | grep ^www | awk '{print "The subdomain www is a", $4, "record and points to", $5}'
        dig lb-01."$1" | grep ^lb-01 | awk '{print "The subdomain lb-01 is a", $4, "record and points to", $5}'
        dig web-01."$1" | grep ^web-01 | awk '{print "The subdomain web-01 is a", $4, "record and points to", $5}'
        dig web-02."$1" | grep ^web-02 | awk '{print "The subdomain web-02 is a", $4, "record and points to", $5}'
    else
		dig "$2"."$1" +noall +answer | awk '{print "The subdomain '"$2"' is a", $4 " record and points to", $5}'
    fi
}
subinfo "$1" "$2"
