#!/usr/bin/env bash
# displays information about subdomains.

subinfo(){
    sublist=("www" "lb-01" "web-01" "web-02")
    if [ "$#" -eq 1 ]; then
        for i in "${sublist[@]}"; do
            dig "$i"."$1" +noall +answer | awk '{print "The subdomain '"$i"' is a", $4, "record and points to", $5}'
        done
    else
        dig "$2"."$1" +noall +answer | awk '{print "The subdomain '"$2"' is a", $4 " record and points to", $5}'
    fi
}
subinfo "$1" "$2"
