#!/usr/bin/env bash
# Install nginx on web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
apt-get -y update
apt-get -y install nginx
chmod -R 777 /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
