#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update
sudo apt-get -y install nginx
echo "<!DOCTYPE html>
    <html>
    <head>
    </head>
    <body>
        <p>Hello World!</p>
    </body>
    </html>" | sudo tee /var/www/html/index.html
service nginx start
