#!/usr/bin/env bash
# Installs nginx server and configures redirection
sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.html

# handles permanent redirection
str1="server_name _;\n\trewrite ^\/redirect_me ^\/gnu.org permanent;"
sudo sed -i "s/server_name _;/$str1/" /etc/nginx/sites-available/default

sudo service nginx restart
