#!/usr/bin/env bash
# Installs and configures HAProxy

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_original

str1="frontend tas_frontend\n\tbind *:80\n\tmode http\n\tdefault_backend tas_backend\n\n"
str2="\nbackend tas_backend\n\tbalance roundrobin\n\tserver 168185-web-01 35.175.135.227 check\n\tserver 168185-web-02 54.87.236.184 check"

echo "$str1$str2" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
