#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.

SAVE=$(date +%d-%m-%Y).tar.gz
mysqldump --all-databases -uroot -p"$1" > backup.sql
tar -cfz "$SAVE" backup.sql
