#!/usr/bin/env bash
# Makes nginx run and listen on port 80 of all the server’s active IPv4 IPs
sudo ln -f -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
