#!/usr/bin/env bash
# A shorter way to configures nginx to listen on port 80 of all the server’s active IPv4 IPs
sudo sed -i 's/8080/80/g' /etc/nginx/sites-availabled/default
sudo service nginx start
echo "" > /var/run/nginx.pid
