#!/usr/bin/env bash
# displays a list of currently running processes.
# shellcheck disable=SC2009
#
#Requirements:
#
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy
# displays lines containing the bash word,
ps auxf | grep "bash"
