#!/usr/bin/env bash
# 100-read_and_cut: displays the content of the file /etc/passwd
# The script displays:
# 1. username
# 2. user id
# 3. Home directory path for the user

filename=/etc/passwd
while IFS=: read -r f1 _ f3 _ _ f6 _
do
	echo "$f1:$f3:$f6"
done < $filename
