#!/usr/bin/env bash
# 101-tell_the_story_of_passwd: displays the content of the file /etc/passwd
#+ in a story mode

file="/etc/passwd"
while IFS=: read -r USERNAME PASSWORD USER_ID GID UID_INFO HOME_DIR COMMAND
do
	echo "The user $USERNAME is part of the $GID gang, lives in"
	echo "$HOME_DIR and rides $COMMAND.$USER_ID's place is protected by the "
	echo "passcode $PASSWORD, more info about the user here: $UID_INFO"
done < "$file"
