#!/usr/bin/env bash
# 102-lets_parse_apache_logs: displays the visitor IP along with the HTTP status code from the Apache log file.
#+ Requirement:
#+ Format: IP HTTP_CODE
#+  in a list format

awk -F' ' '{ print $1 " " $9 }' apache-access.log
