#!/usr/bin/env bash
# 5-4_bad_luck_8_is_your_chance: loops from 1 to 10 and:
#+ 1. displays bad luck for the 4th loop iteration
#+ 2. displays good luck for the 8th loop iteration
#+ 3. displays Best School for the other iterations

x=1
while [ $x -le 10 ]
do
if [ $x -eq 4 ]
then
echo "bad luck"
elif [ $x == 8 ]
then
echo "good luck"
else
echo "Best School"
fi
x=$((x + 1))
done
