#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
while [ "$hour" -lt 13 ]; do
	echo "Hour: $hour"
	min=1
	while [ "$min" -lt 60 ]; do
		echo "$min"
		((min+=1))
	done
	((hour+=1))
done
