#!/usr/bin/env bash
# 8-for_ls: displays:
#+ The content of the current directory
#+ In a list format
#+ Where only the part of the name after the first dash is displayed
for i in *
do
	echo "$i" | cut -f 2- -d "-"
done
