#!/usr/bin/env bash
# 9-to_file_or_not_to_file: gives information about the school file

filename=school
if [ ! -e "${filename}" ]; then
	echo "school file does not exist"
else
	echo "school file exists"
	if [ ! -s "${filename}" ] && [ -f "${filename}" ]; then
		echo "school file is empty"
		echo "school is a regular file"
	elif [ -d "${filename}" ]; then
		echo "school file is not empty"
	else
		echo "school file is not empty"
		echo "school is a regular file"
	fi
	if [ -e "${filename}" ] || [ ! -f "${filename}" ]; then
		:
	fi
fi
