#!/usr/bin/env bash
# 0-change_your_home_IP: configures an Ubuntu server
#+ with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.bck
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts.bck
sed -i "\$a8.8.8.8	facebook.com" /etc/hosts.bck
cp -f /etc/hosts.bck /etc/hosts
