#!/usr/bin/env bash
# Runs nginx as the nginx user.
sudo pkill apache2
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 766 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
